apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    selector: example-mysql-data-claim
  name: example-mysql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi